version: 2.1
orbs:
  python: circleci/python@3.0.0

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run GitHub API Accessor
          command: python cs567_hw03a/github_api_accessor.py

workflows:
  build_test_deploy:
    jobs:
      - build_and_test